spring:
  application:
    name: NinhoAPI
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            format_sql: true

jwt:
    secretKey: ${JWT_SECRET}
    expiration: 3600000 # 1 hour in milliseconds
    issuer: NinhoAPI